backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Preview Image", name: "image", widget: "image"}
      - { label: "Preview Image Alt Text", name: "imgAlt", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Is Blog Post", name: "isPost", widget: "hidden", default: true }
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", required: false}
      - { label: "Preview Image", name: "image", widget: "image"}
      - { label: "Preview Image Alt Text", name: "imgAlt", widget: "string"}
      - { label: "Tags", name: "tags", widget: "list", default: ["project"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Is Project", name: "isProject", widget: "hidden", default: true }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string", default: "/{title}/index.html" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string", default: "{title}"}
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Include Second Section?", name: "hasSecond", widget: "boolean", required: false }
      - { label: "Second Section Header", name: "secondHeader", widget: "string", required: false }
      - { label: "Second Section", name: "secondSection", widget: "markdown", required: false }
      - { label: "Include Collection List?", name: "hasCollection", widget: "boolean", required: false }
      - { label: "Collection Name", name: "collectionName", widget: "string", required: false }
  #features
  - name: "features"
    label: "Feature"
    folder: "features"
    create: true # Change to true to allow editors to create new features
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Alt Text", name: "imgAlt", widget: "string"}
      - { label: "Snippet", name: "snippet", widget: "string" }
      - { label: "Link Text", name: "linkText", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Is Feature", name: "isFeature", widget: "boolean", default: true, hidden: true }
  - name: "footer"
    label: "Footer Elements"
    folder: "footerElements"
    create: true
    fields:
      - { label: "Content", name: "content", widget: "markdown"}
      - { label: "Display Order (1-5)", name: "order", widget: "number" }